### ISSUE TITLE
Avoid recursive loops when detecting commits

### ISSUE THREAD

**Issue by dgarijo** [Autontool/auton#14]
Right now Auton is watching the readme file of a repo.
If auton changes the file, it detects it as a new change, triggering a continuos loop of merge requests.
If Auton is the one who committed the file (even if the merge request was accepted by someone else), then this should not trigger any further action by auton.

Note that this issue will not normally happen, as you will be watching the OWL files, and Auton is not expected to change those files.

**Comment by ahmad88me** [comment]
fixed, will only monitor files with specific extensions
