### ISSUE TITLE
Produce a taxonomy diagram

### ISSUE THREAD

**Issue by dgarijo** [Autontool/auton#20]
This is a sample configuration on how to achieve it:
pathToDot=/usr/local/bin/dot;
pathToTempDir=/tmp;
imageSize=1501;
rankdir=LR;

########
#shapes#
########

#classShape=diamond;
#individualShape=diamond;
#literalShape=box;
#arrowhead=normal;
#arrowtail=normal;
#arrowdir=forward;

########
#colors#
########

#classColor=orange;
#individualColor=orange;
#literalColor=blue;
#arrowColor=blue;

#######
#files#
#######

generateGvFile=true;
generateGraphMLFile=false;

#############
#RDF options#
#############

nodeNameMode=localname;
ignoreLiterals=true;
ignoreRdfType=false;
synthesizeObjectProperties=false;

#######
#lists#
#######

includeOnlyElementList=[
<
http://www.w3.org/2000/01/rdf-schema#subClassOf
>
];

**Comment by ahmad88me** [comment]
Done
