### ISSUE TITLE
Configuration file for Auton

### ISSUE THREAD

**Issue by dgarijo** [Autontool/auton#21]
Auton should accept a configuration file for configuring:
- Whether the user wants Auton to do the drawings.
- Whether the user wants auton to regenerate the doc.
- Whether the user wants auton to open issues.
I think the file is necessary because maybe there is an intensive development at some point and the users don't want the tool to regenerate everything constantly. But then, when they are done with the editing they want to regenerate everything again.

**Comment by ahmad88me** [comment]
Done
