### ISSUE TITLE
I have tested an ontology, it didn't produce anything

### ISSUE THREAD

**Issue by dgarijo** [Autontool/auton#22]
I have pushed a sample ontology here: https://github.com/dgarijo/test
Auton did a merge request, but nothing was changed and no diagrams where attached.

Maybe there was some error?

**Comment by dgarijo** [comment]
Now no more pull requests have been made to the repository.

**Comment by ahmad88me** [comment]
@dgarijo , Because 
1-Auton where only work with files ending with .rdf, now I changed it to work with files end with .rdf or .owl
2-The drawing or the owl file is giving errors

**Comment by dgarijo** [comment]
Ah, it should be working with files ending in .ttl, .owl or .rdf.

**Comment by ahmad88me** [comment]
Added .ttl and solved

**Comment by dgarijo** [comment]
I reopen this issue in order to:
a) Solve the issue with the configuration file, which messed up the diagram creation
b) Widoco documentation integration

**Comment by ahmad88me** [comment]
@dgarijo The configuration file issues is fixed, and the widoco documentation is integrated.
