### ISSUE TITLE
List of observed repositories

### ISSUE THREAD

**Issue by mariapoveda** [Autontool/auton#25]
AutonTool interface has to provide a list of repositories being observed, and the time of the last change (ordered by this timestamp)

**Comment by dgarijo** [comment]
+1. Once we polish the application, we can discuss if the server should have user authentication for watching repository detailes and statuses.

**Comment by ahmad88me** [comment]
Added, it will appear at the bottom on the page

**Comment by dgarijo** [comment]
My repository, dgarijo/test, does not appear. Neither does Maria's.
