### ISSUE TITLE
When monitoring repositories in the server, show what is being monitored

### ISSUE THREAD

**Issue by dgarijo** [Autontool/auton#30]
That is, if the documentation is enabled, the diagram creation is enabled or the oops evaluation is enabled. This can be seen in the auton config file.

**Comment by ahmad88me** [comment]
@dgarijo I added it, once the page is loaded you can scroll down to see the table

**Comment by dgarijo** [comment]
Fantastic @ahmad88me!!. I would like to see it wit yes/no instead of the true/false, but for the moment it is ok.

**Comment by mariapoveda** [comment]
The scroll only applies to the table in the bottom. As the table is transparent if the screen is small enough the table goes on top of the text above and the text is not readable.

**Comment by mariapoveda** [comment]
I would apply the scroll to the whole page, not fix the first part.

**Comment by ahmad88me** [comment]
@dgarijo @mariapoveda Done
