### ISSUE TITLE
Use the new bundle structure

### ISSUE THREAD

**Issue by dgarijo** [Autontool/auton#35]
for each owl file: 
auton_ontology_file_name
		|
		|- diagrams
			|
			|-Taxonomy (3 files with the png, graphml and dot)
			|-Class (3 files)
			|-Config (2 files: tax.conf and class.conf)
		|-Documentation (current structure is ok)
		|-Evaluation (current structure is ok)
		|-Configuration (auton config will go here).

**Comment by ahmad88me** [comment]
Done
