### ISSUE TITLE
Refine OOPS! Message

### ISSUE THREAD

**Issue by dgarijo** [Autontool/auton#44]
The title of the issue should be "OOPS! Evaluation".
The content should be something like:
"OOPS has encountered [number] pitfalls and [number] warnings.
The Pitfalls are the following:<list of the name of the pitfalls. Bulleted list>.
The warnings are the following: <list of the name of the pitfalls. Bulleted list>.
For more information, see [link to the html page produced by Widoco]

**Comment by mariapoveda** [comment]
The Pitfalls are the following:
    * pitfall title 1
    * pitfall title 2
  .....
The warnings are the following: .

**Comment by ahmad88me** [comment]
Done
