### ISSUE TITLE
Configure Widoco to execute files with accents properly

### ISSUE THREAD

**Issue by dgarijo** [Autontool/auton#54]
For example, here: https://raw.githubusercontent.com/opencitydata/vocabularios-datos-abiertos/master/turismo/alojamiento/0.1/alojamiento.owl the encoding is not properly shown.

This could be solved with the -Dfile.encoding=utf-8 option when executing the JAR.

**Comment by ahmad88me** [comment]
@dgarijo I'm getting the below error with Widoco running this command

java -jar /home/ubuntu/Widoco/JAR/widoco-0.0.1-jar-with-dependencies.jar -Dfile.encoding=utf-8 -rewriteAll  -ontFile /home/ubuntu/temp/ahmad88me@gmail.com/turismo/alojamiento/0.1/alojamiento.owl -outFolder /home/ubuntu/temp/ahmad88me@gmail.com/auton/turismo/alojamiento/0.1/alojamiento.owl/documentation -confFile /home/ubuntu/temp/ahmad88me@gmail.com/auton/turismo/alojamiento/0.1/alojamiento.owl/documentation/alojamiento.owl.widoco.conf

Command-Dfile.encoding=utf-8 not recognized.

**Comment by ahmad88me** [comment]
@idafensp ar2dtool is also giving an error for this owl file

**Comment by dgarijo** [comment]
I have just tried and it works. Maybe it's a java special feature of the distribution you are running. I have also tried it in a Unix environment and it works too.

**Comment by idafensp** [comment]
It seems to be working for me also. Could you upload your conf file?

**Comment by ahmad88me** [comment]
@idafensp I'm sorry idafensp, the problem was related to a change I made on the ontology file. Thank you
