### ISSUE TITLE
Proper configuration of Class Diagram for Ar2dtool

### ISSUE THREAD

**Issue by dgarijo** [Autontool/auton#55]
1) Download the latest JAR: https://github.com/idafensp/ar2dtool/tree/master/bin
2) Use this configuration file. It fixes prefixes issues and filters some unwanted elements. Do NOT forget the "-gml" flag to produce the gml file :) :

pathToDot=/usr/local/bin/dot;
pathToTempDir=/tmp;
imageSize=1501;
rankdir=LR;

########
#shapes#
########

#classShape=diamond;
#individualShape=diamond;
#literalShape=box;
#arrowhead=normal;
#arrowtail=normal;
#arrowdir=forward;

########
#colors#
########

classColor=orange;
#individualColor=orange;
#literalColor=blue;
#arrowColor=blue;

#############
#RDF options#
#############

nodeNameMode=prefix;
ignoreLiterals=true;
ignoreRdfType=true;
synthesizeObjectProperties=true;

#######
#lists#
#######

ignoreElementList=[<http://www.w3.org/2000/01/rdf-schema#subClassOf, http://www.w3.org/2000/01/rdf-schema#isDefinedBy, http://www.w3.org/2000/01/rdf-schema#subPropertyOf, http://www.w3.org/2002/07/owl#inverseOf>];

**Comment by ahmad88me** [comment]
New jar is used and it generates gml now
